#!/usr/bin/env python3
"""
Regenerate the mana symbol drawables from Scryfall's own SVGs.

    python tools/mana_symbols.py

The card view sets mana costs and rules text in real Magic symbols, and the app
is offline - the whole point of it - so linking Scryfall's hosted SVGs the way a
web front end would is not available. They are converted to Android vector
drawables at build time instead and shipped in the APK.

The conversion is straightforward because Scryfall's symbols are: one `viewBox
0 0 100 100`, a filled circle for the disc, and one or two filled paths for the
glyph. `pathData` takes SVG path syntax verbatim, so only the circle has to be
rewritten - as two arcs, which is the same shape by another spelling.

Which symbols get built is decided by the corpus, not by a list somebody has to
remember to update: every `{...}` token that appears in a mana cost or a rules
text in `momir.db`. That is 60 of Scryfall's ~110 at the time of writing, and it
means a set that adds a symbol brings it in on the next build.

Also writes `ManaSymbols.kt`, so the token-to-drawable map is generated from the
same pass rather than hand-maintained beside it.
"""
import json
import os
import re
import sqlite3
import sys
import urllib.request
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DB = os.path.join(HERE, "momirdeck", "out", "momir.db")
DRAWABLE = os.path.join(ROOT, "app", "src", "main", "res", "drawable")
KOTLIN = os.path.join(
    ROOT, "app", "src", "main", "java", "software", "zeasy", "momir", "ui", "ManaSymbols.kt"
)

SYMBOLOGY = "https://api.scryfall.com/symbology"
AGENT = "MomirSunmi/1.0 (+https://github.com/MagieAlex/MomirSunmi)"

TOKEN = re.compile(r"\{([^{}]+)\}")

# Used when there is no corpus to read - the set the 2026-08 corpus needed.
FALLBACK = [
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13",
    "14", "15", "16", "20", "X", "W", "U", "B", "R", "G", "C", "S", "E", "H",
    "P", "Q", "T", "W/U", "W/B", "U/B", "U/R", "B/R", "B/G", "R/G", "R/W",
    "G/W", "G/U", "2/W", "2/U", "2/B", "2/R", "2/G", "W/P", "U/P", "B/P",
    "R/P", "G/P", "C/W", "C/U", "C/B", "C/R", "C/G", "G/U/P", "G/W/P",
    "R/G/P", "R/W/P",
]


def needed_tokens() -> "list[str]":
    """Every symbol the corpus actually uses, or the fallback list."""
    if not os.path.exists(DB):
        print(f"no corpus at {DB}, using the built-in list")
        return sorted(FALLBACK)
    conn = sqlite3.connect(DB)
    found = set()
    for table, columns in (("cards", ("mana_cost", "oracle_text")), ("tokens", ("oracle_text",))):
        for row in conn.execute(f"select {', '.join(columns)} from {table}"):
            for value in row:
                found.update(TOKEN.findall(value or ""))
    conn.close()
    return sorted(found)


def slug(token: str) -> str:
    """`{W/U}` -> `mana_wu`, `{2}` -> `mana_2`. Resource names are [a-z0-9_]."""
    return "mana_" + token.lower().replace("/", "").replace("∞", "inf")


def fetch(url: str, accept: str = "*/*") -> bytes:
    # Scryfall wants both headers on every request and answers 400 without them.
    request = urllib.request.Request(url, headers={"User-Agent": AGENT, "Accept": accept})
    return urllib.request.urlopen(request, timeout=30).read()


def circle_path(cx: float, cy: float, r: float) -> str:
    """A circle as two arcs, which is how a vector drawable spells one."""
    return (f"M{cx - r},{cy} a{r},{r} 0 1,0 {2 * r},0 a{r},{r} 0 1,0 {-2 * r},0 Z")


def to_vector(svg: bytes, size_dp: int = 24) -> str:
    root = ET.fromstring(svg)
    box = (root.get("viewBox") or "0 0 100 100").split()
    width, height = float(box[2]), float(box[3])

    paths = []

    def walk(element, fill, rule):
        fill = element.get("fill", fill)
        rule = element.get("fill-rule", rule)
        tag = element.tag.split("}")[-1]

        if tag == "circle" and fill and fill != "none":
            paths.append((circle_path(
                float(element.get("cx", 0)), float(element.get("cy", 0)),
                float(element.get("r", 0)),
            ), fill, rule))
        elif tag == "path" and fill and fill != "none":
            data = element.get("d")
            if data:
                paths.append((data, fill, rule))

        for child in element:
            walk(child, fill, rule)

    walk(root, root.get("fill"), root.get("fill-rule"))
    if not paths:
        raise ValueError("no filled shapes")

    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tools/mana_symbols.py from Scryfall's own SVG. Do not edit. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{size_dp}dp"',
        f'    android:height="{size_dp}dp"',
        f'    android:viewportWidth="{width:g}"',
        f'    android:viewportHeight="{height:g}">',
    ]
    for data, fill, rule in paths:
        out.append("    <path")
        out.append(f'        android:fillColor="{fill}"')
        if rule == "evenodd":
            out.append('        android:fillType="evenOdd"')
        out.append(f'        android:pathData="{data.strip()}" />')
    out.append("</vector>")
    return "\n".join(out) + "\n"


def kotlin_map(entries: "list[tuple[str, str]]") -> str:
    lines = [
        "package software.zeasy.momir.ui",
        "",
        "import android.content.Context",
        "import android.graphics.drawable.Drawable",
        "import android.text.Spannable",
        "import android.text.SpannableStringBuilder",
        "import androidx.core.content.ContextCompat",
        "import software.zeasy.momir.R",
        "",
        "/**",
        " * Magic's mana symbols, as the game draws them.",
        " *",
        " * The drawables are Scryfall's own SVGs converted to vector drawables by",
        " * tools/mana_symbols.py, which also generates the table below - so a symbol",
        " * cannot be in one and missing from the other. Rebuild both with:",
        " *",
        " * ```",
        " * python tools/mana_symbols.py",
        " * ```",
        " *",
        " * They are shipped rather than fetched because this app works with no network",
        " * at all, which is the whole point of it. A slip prints the same costs as",
        " * letters - thermal paper has no mana font, and 48 mm has no room for one.",
        " */",
        "object ManaSymbols {",
        "",
        "    /** Scryfall's token, without the braces, to the drawable that draws it. */",
        "    private val SYMBOLS: Map<String, Int> = mapOf(",
    ]
    for token, name in entries:
        lines.append(f'        "{token}" to R.drawable.{name},')
    lines += [
        "    )",
        "",
        "    /** The `{...}` runs this can draw. */",
        "    private val TOKEN = Regex(\"\\\\{([^{}]+)\\\\}\")",
        "",
        "    /**",
        "     * Replaces every `{...}` in [text] with its symbol, sized to [sizePx].",
        "     *",
        "     * Spans already on the text - the italics reminder text carries - survive,",
        "     * because the replacement happens in place and backwards, so no earlier",
        "     * offset moves under a span that was set on it.",
        "     *",
        "     * A token with no drawable is left exactly as it was written. Scryfall",
        "     * invents symbols faster than a corpus gets rebuilt, and `{∞}` spelled out",
        "     * is better than a gap.",
        "     */",
        "    fun render(context: Context, text: CharSequence, sizePx: Int): CharSequence {",
        "        val matches = TOKEN.findAll(text).toList()",
        "        if (matches.isEmpty()) return text",
        "",
        "        val out = SpannableStringBuilder(text)",
        "        for (match in matches.asReversed()) {",
        "            val drawable = drawable(context, match.groupValues[1], sizePx) ?: continue",
        "            val start = match.range.first",
        "            out.replace(start, match.range.last + 1, PLACEHOLDER)",
        "            out.setSpan(",
        "                CenteredImageSpan(drawable),",
        "                start,",
        "                start + PLACEHOLDER.length,",
        "                Spannable.SPAN_EXCLUSIVE_EXCLUSIVE,",
        "            )",
        "        }",
        "        return out",
        "    }",
        "",
        "    fun drawable(context: Context, token: String, sizePx: Int): Drawable? {",
        "        val id = SYMBOLS[token.uppercase()] ?: return null",
        "        val drawable = ContextCompat.getDrawable(context, id) ?: return null",
        "        drawable.setBounds(0, 0, sizePx, sizePx)",
        "        return drawable",
        "    }",
        "",
        "    /** One character to hang the span on. A space keeps the wrap points honest. */",
        "    private const val PLACEHOLDER = \" \"",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    tokens = needed_tokens()
    print(f"{len(tokens)} symbols wanted")

    print("fetching symbology...")
    symbology = json.loads(fetch(SYMBOLOGY, "application/json"))
    uris = {
        entry["symbol"].strip("{}"): entry["svg_uri"]
        for entry in symbology["data"]
        if entry.get("svg_uri")
    }

    os.makedirs(DRAWABLE, exist_ok=True)
    entries, missing = [], []
    for token in tokens:
        uri = uris.get(token)
        if not uri:
            missing.append(token)
            continue
        name = slug(token)
        try:
            xml = to_vector(fetch(uri))
        except Exception as error:  # noqa: BLE001 - report and carry on
            print(f"  {token}: {error}")
            missing.append(token)
            continue
        with open(os.path.join(DRAWABLE, name + ".xml"), "w", encoding="utf-8") as handle:
            handle.write(xml)
        entries.append((token, name))

    with open(KOTLIN, "w", encoding="utf-8") as handle:
        handle.write(kotlin_map(entries))

    print(f"wrote {len(entries)} drawables and ManaSymbols.kt")
    if missing:
        print(f"no symbol for: {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
